### ISSUE TITLE
Secure Flag for .list Parameter For Arrays of Config Objects

### ISSUE THREAD

**Issue by corim707** [ponycode/pony-config#1]
It's not currently possible to use the "secure" list in reference to an array of config objects as it does a pure index of check and not a pattern match.

Given a config such as:
var config = require("pony-config");
config.useObject( {properties:
  [
    {id:1, mySuperSecureProperty:"suuuuuper secret#1"},
    {id: 2, mySuperSecureProperty:"suuuuuper secret#2"}
  ]
});

config.list( {secure: ['mySuperSecureProperty']});

You will see something like below print in the logs:
─properties :  [USE-OBJECT]
├───├───0 : 
├───├───├───id : 1
├───├───├───mySuperSecureProperty : suuuuuper secret#1
├───├───1 : 
├───├───├───id : 2
├───├───├───mySuperSecureProperty : suuuuuper secret#2

**Comment by homedad** [comment]
Ross, this is solved by using the keypath to correctly identify either the entire array, 'properties', or an array index 'properties.0'. You are correct that pony-config doesn't do a pattern match. It uses keypaths from the root. As follows for your example:

`config.list( { secure: ['properties.0', 'properties.1'] }`
or
`config.list( { secure: ['properties'] })`
