### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by depoulo** [ponycode/pony-config#2]
Hey, just wanted to let you know that regardless of the low number of watches and stars, there are people out there using your library, and for them it's a bit of a PITA that recently every patch level version brings breaking changes like case (in)sensitivity or renaming a bunch of public API methods, especially since there's no easy way to get a change log or even a git diff between two versions.

Please, this is no offense, if you don't want to use semver, that's fine for me, but then at least I know what to do.

**Comment by erikmueller** [comment]
I guess `2.0.0` should not have been `2.0.0` since it does not seem to contain breaking changes but `2.0.2` does (published wrong code?). So `2.0.2` should have been `3.0.0` imho.

That's at least what I think happened. But yeah, small changelo would be aweseome 👍

**Comment by homedad** [comment]
Thanks. My bad.

We use the module a lot, but I’m not very good at semver management, and I underestimated the number of consumers our module had.

I inadvertently published code midway through some changes and created confusion.

I’ll be using semver more responsibly in the future, and I’ll start a changelog.

-scott.e

Scott Eklund
VP Engineering, pHin
408-429-3722

**Comment by homedad** [comment]
Thanks. My bad.

We use the module a lot, but I’m not very good at semver management, and I underestimated the number of consumers our module had.

I inadvertently published code midway through some changes and created confusion.

I’ll be using semver more responsibly in the future, and I’ll start a changelog.

-scott.e

Scott Eklund
VP Engineering, pHin
408-429-3722

**Comment by jkennedy1980** [comment]
Hey guys. How about some stars or watches? We didn't think anyone else was using this.
